### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by codeinhere123** [WantEducation/arrowDetection-by-openCV#1]

**Comment by rohitghughtyal** [comment]
Hello Mr Alex,
sorry for the late reply.

Actually basically my project uses a few properties of solid arrow to get
detected.
first all the corner points of arrow are detected using canny detection
method.
In the first for loop, out of all those point 4  point are found which are
basically the points which have max x, y and min x , y distance from (0,0)
i.e the origin.

then this is determined whether the arrow is vertical one or horizontal. By
using the fact that normally distance between  x max and x min point is
more that distance between y max and y min if the arrow is right or left.
Otherwise it is up or down.
Lets say arrow is horizontal
Then this is determined that is arrow that
Whether arrow is right or left.
For that next x max and next x min is found.
Say arrow is right then
Next x max point will  Far from x max

Than

Next x min from x min. Because next x min and x  min are close in the used
picture and definetly are in general.

A comparision can be made to conclude that arrow was right.
Same can be for left arrow. But in this case it would be x min and next x
min that would have more distance between than x max and next x max .

Similary vertical arrow can be taken care of.

Thank you

Regards
Rohit

**Comment by codeinhere123** [comment]
Hi Mr Rohit,

Appreciate your response! Sorry I thought the repo no longer maintained so I closed it instead. 

Regards
Alex

**Comment by rohitghughtyal** [comment]
Hi Mr Alex,

Actually,  I usually don't check github that often. Thats why i didn't
checked that.

Regards
Rohit

**Comment by codeinhere123** [comment]
Dear Mr Rohit, 

Good day! No worries, totally understand that. 

Take care and thanks for the useful script! Truly appreciated.

Regards
Alex
